language: python
dist: xenial

matrix:
  include:
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
  - python: '3.6'
    env: TOXENV=pre-commit

before_install:
- pip install tox codecov

script:
- tox -v

after_success:
- if [ "${TOXENV}" == "py36" ]; then codecov; fi
