basePath: /api

consumes:
- application/json

definitions:
  Alert:
    properties:
      appName:
        description: myApp name
        type: string
      deviceId:
        type: string
      ipAddress:
        type: string
      message:
        type: string
      time:
        type: integer
      type:
        type: string
    required:
    - deviceId
    - ipAddress
    - appName
    - type
    - message
    - time
    type: object
    x-model: Alert

  ApplicationResourceAsk:
    properties:
      cpu:
        type: integer
      memory:
        type: integer
      profile:
        enum:
        - c1.tiny
        - c1.small
        - c1.medium
        - c1.large
        - c1.xlarge
        - custom
        type: string
    required:
    - cpu
    - memory
    - profile
    type: object
    x-model: ApplicationResourceAsk

  DeployMyApp:
    properties:
      appSourceType:
        enum:
        - Docker
        - LOCAL_STORE
        - LXC
        type: string
      name:
        type: string
      sourceAppName:
        type: string
      version:
        type: string
    required:
    - appSourceType
    - name
    - sourceAppName
    - version
    type: object
    x-model: DeployMyApp

  Device:
    allOf:
    - $ref: '#/definitions/DeviceMinimal'
    - properties:
        apps:
          items:
            type: integer
          type: array
        deviceId:
          type: string
        usedCPU:
          type: integer
        usedMEM:
          type: integer
      required:
      - deviceId
      - usedCPU
      - usedMEM
      - apps
      type: object
    type: object
    x-model: Device

  DeviceMinimal:
    properties:
      ipAddress:
        type: string
      password:
        type: string
      port:
        type: string
      username:
        type: string
    required:
    - port
    - ipAddress
    - username
    - password
    type: object
    x-model: DeviceMinimal

  LocalApp:
    properties:
      cpuUsage:
        type: integer
      creationDate:
        type: integer
      localAppId:
        type: string
      memoryUsage:
        type: integer
      profileNeeded:
        enum:
        - c1.tiny
        - c1.small
        - c1.medium
        - c1.large
        - c1.xlarge
        type: string
      published:
        enum:
        - published
        - unpublished
        type: string
      sourceAppName:
        type: string
      version:
        type: string
    required:
    - creationDate
    - localAppId
    - version
    - published
    - profileNeeded
    - cpuUsage
    - memoryUsage
    - sourceAppName
    type: object
    x-model: LocalApp


  MyAppAction:
    maxProperties: 1
    minProperties: 1
    properties:
      deploy:
        $ref: '#/definitions/MyAppActionDeployDevices'
      start:
        additionalProperties: false
        type: object
      stop:
        additionalProperties: false
        type: object
      undeploy:
        $ref: '#/definitions/MyAppActionUndeployDevices'
    type: object
    x-model: MyAppAction

  MyAppActionDeployDevices:
    properties:
      devices:
        items:
          $ref: '#/definitions/MyAppActionDeployItem'
        type: array
    type: object
    x-model: MyAppActionDeployDevices

  MyAppActionDeployItem:
    properties:
      deviceId:
        type: string
      resourceAsk:
        properties:
          resources:
            $ref: '#/definitions/ApplicationResourceAsk'
        type: object
    type: object
    x-model: MyAppActionDeployItem

  MyAppActionUndeployDevices:
    properties:
      devices:
        description: List Device identifiers to whom uninstall the MyApp
        items:
          type: string
        type: array
    required:
    - devices
    type: object
    x-model: MyAppActionUndeployDevices

info:
  description: |
    The APIs are extracted with best effort,
    we do not have the ambition to claim that the following
    are CISCO''s Fog Director complete APIs.
  title: APIs for Cisco's Fog Director
  version: '0.0'

paths:
  /v1/appmgr/alerts:
    get:
      description: Retrieve all the currently available alerts
      operationId: get_v1_appmgr_alerts
      responses:
        '200':
          description: HTTP/200
          schema:
            properties:
              data:
                items:
                  $ref: '#/definitions/Alert'
                type: array
            required:
            - data
      security:
      - XTokenId: []
      tags:
      - v1

  /v1/appmgr/apps/{local_application_id}:{version}:
    delete:
      description: Remove the Application from the Local Store
      operationId: delete_v1_appmgr_apps_local_application_id_version
      parameters:
      - in: path
        name: local_application_id
        required: true
        type: string
      - in: path
        name: version
        required: true
        type: string
      responses:
        '200':
          description: HTTP/200
      security:
      - XTokenId: []
      tags:
      - v1

  /v1/appmgr/devices:
    get:
      description: Retrieve the devices matching the filtering rules
      operationId: get_v1_appmgr_devices
      parameters:
      - in: query
        name: limit
        required: false
        type: integer
      - in: query
        name: offset
        required: false
        type: integer
      responses:
        '200':
          description: HTTP/200
          schema:
            properties:
              data:
                items:
                  $ref: '#/definitions/Device'
                type: array
            required:
            - data
            type: object
      security:
      - XTokenId: []
      tags:
      - v1

    post:
      description: Add a Device on the Infrastructure
      operationId: post_v1_appmgr_devices
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/DeviceMinimal'
      responses:
        '200':
          description: HTTP/200
          schema:
            $ref: '#/definitions/Device'
      security:
      - XTokenId: []
      tags:
      - v1

  /v1/appmgr/devices/{device_id}:
    delete:
      description: Remove the Device from the Infrastructure
      operationId: delete_v1_appmgr_devices_device_id
      parameters:
      - in: path
        name: device_id
        required: true
        type: string
      responses:
        '200':
          description: Removed device
          schema:
            $ref: '#/definitions/Device'
      security:
      - XTokenId: []
      tags:
      - v1

  /v1/appmgr/localapps:
    get:
      description: Retrive the Local Application available in the Local Store
      operationId: get_v1_appmgr_localapps
      parameters:
      - in: query
        name: limit
        required: false
        type: integer
      - in: query
        name: offset
        required: false
        type: integer
      responses:
        '200':
          description: HTTP/200
          schema:
            properties:
              data:
                items:
                  $ref: '#/definitions/LocalApp'
                type: array
            required:
            - data
            type: object
      security:
      - XTokenId: []
      tags:
      - v1

  /v1/appmgr/localapps/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload the application archive to the Local Store
      operationId: post_v1_appmgr_localapps_upload
      parameters:
      - in: header
        name: X-Publish-On-Upload
        required: false
        type: boolean
      - in: formData
        name: file
        required: true
        type: file
      responses:
        '200':
          description: HTTP/200
          schema:
            $ref: '#/definitions/LocalApp'
      security:
      - XTokenId: []
      tags:
      - v1

  /v1/appmgr/localapps/{local_application_id}:{version}:
    put:
      description: Update the Application status (publish, unpublish)
      operationId: put_v1_appmgr_localapps_local_application_id_version
      parameters:
      - in: path
        name: local_application_id
        required: true
        type: string
      - in: path
        name: version
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/LocalApp'
      responses:
        '200':
          description: HTTP/200
          schema:
            $ref: '#/definitions/LocalApp'
      security:
      - XTokenId: []
      tags:
      - v1

  /v1/appmgr/myapps:
    get:
      description: Get the myapp created in the system
      operationId: get_v1_appmgr_myapps
      parameters:
      - in: query
        name: searchByName
        required: false
        type: string
      responses:
        '200':
          description: HTTP/200
          schema:
            properties:
              data:
                items:
                  properties:
                    myAppId:
                      type: integer
                    name:
                      type: string
                  required:
                  - myAppId
                  - name
                type: array
            required:
            - data
            type: object
      security:
      - XTokenId: []
      tags:
      - v1

    post:
      description: Create a new deployment hook
      operationId: post_v1_appmgr_myapps
      parameters:
      - description: Parameter added by FogDirSim to permit to specify minimal amount of job required to consider the myapp up and running
        in: query
        name: minjobs
        required: false
        type: integer
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/DeployMyApp'
      responses:
        '200':
          description: MyApp correctly created
          schema:
            properties:
              myAppId:
                type: integer
              name:
                type: string
            required:
            - myAppId
            - name
      security:
      - XTokenId: []
      tags:
      - v1

  /v1/appmgr/myapps/{my_app_id}:
    delete:
      description: Remove the myApp if it is not installed on any device, returns error otherwise
      operationId: delete_v1_appmgr_myapps_my_app_id
      parameters:
      - description: myApp identifier to remove
        in: path
        name: my_app_id
        required: true
        type: integer
      responses:
        '200':
          description: HTTP/200
          schema:
            properties:
              myAppId:
                type: integer
              name:
                type: string
            required:
            - myAppId
            - name
      security:
      - XTokenId: []
      tags:
      - v1

  /v1/appmgr/myapps/{my_app_id}/action:
    post:
      description: Manage the myapp state applying action on it
      operationId: post_v1_appmgr_myapps_my_app_id_action
      parameters:
      - description: myApp identifier
        in: path
        name: my_app_id
        required: true
        type: integer
      - default: normal
        description: Simulator job intensitivy profile used to represent an heavy resources application usage
        enum:
        - quiet
        - normal
        - heavy
        in: query
        name: job_intensivity
        required: false
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/MyAppAction'
      responses:
        '200':
          description: HTTP/200
          schema:
            properties:
              jobId:
                type: string
            required:
            - jobId
            type: object
      security:
      - XTokenId: []
      tags:
      - v1

  /v1/appmgr/tokenservice:
    post:
      operationId: post_v1_appmgr_tokenservice
      parameters:
      - description: Basic Authentication Header
        in: header
        name: Authorization
        type: string
      responses:
        '200':
          description: HTTP/200
          schema:
            properties:
              expiryTime:
                type: integer
              serverEpochTime:
                type: integer
              token:
                type: string
            required:
            - token
            - expiryTime
            - serverEpochTime
            type: object
      tags:
      - v1

  /v1/appmgr/tokenservice/{token}:
    delete:
      operationId: delete_v1_appmgr_tokenservice_token
      parameters:
      - description: token to delete
        in: path
        name: token
        required: true
        type: string
      responses:
        '200':
          description: HTTP/200
      security:
      - XTokenId: []
      tags:
      - v1

produces:
- application/json

schemes:
- http
- https

securityDefinitions:
  XTokenId:
    description: Token provided to the user during the login phase. The token will provide the right user context to the server.
    in: header
    name: X-Token-Id
    type: apiKey

swagger: '2.0'
