basePath: /api

consumes:
- application/json

definitions:
  AggregatedDeviceMetric:
    properties:
      averageCpuUsed:
        format: float
        minimum: 0
        type: number
      averageMemUsed:
        format: float
        minimum: 0
        type: number
      averageMyAppCount:
        format: float
        minimum: 0
        type: number
      criticalCpuUsagePercentage:
        format: float
        maximum: 1
        minimum: 0
        type: number
      criticalMemUsagePercentage:
        format: float
        maximum: 1
        minimum: 0
        type: number
      device:
        $ref: '#/definitions/DeviceMinimal'
      deviceDownPercentage:
        format: float
        maximum: 1
        minimum: 0
        type: number
      deviceEnergyConsumption:
        format: float
        minimum: 0
        type: number
    required:
    - device
    - averageCpuUsed
    - averageMemUsed
    - averageMyAppCount
    - criticalCpuUsagePercentage
    - criticalMemUsagePercentage
    - deviceDownPercentage
    - deviceEnergyConsumption
    type: object
    x-model: AggregatedDeviceMetric

  AggregatedDeviceMetricResponse:
    properties:
      iteration_count:
        type: integer
      metrics:
        items:
          $ref: '#/definitions/AggregatedDeviceMetric'
        type: array
    required:
    - iteration_count
    - metrics
    type: object
    x-model: AggregatedDeviceMetricResponse

  AggregatedMyAppMetric:
    properties:
      alertStatistics:
        $ref: '#/definitions/AlertStatus'
      installedTimePercentagePerDevice:
        additionalProperties:
          format: float
          maximum: 1
          minimum: 0
          type: number
        description: Mapping of all the devices and the percentage of time in which the myApp was installed
      myApp:
        $ref: '#/definitions/MyAppMinimal'
      startTimePercentagePerDevice:
        additionalProperties:
          format: float
          maximum: 1
          minimum: 0
          type: number
        description: Mapping of all the devices and the percentage of time in which the myApp was started
      uptimePercentage:
        format: float
        maximum: 1
        minimum: 0
        type: number
    required:
    - myApp
    - alertStatistics
    - startTimePercentagePerDevice
    - installedTimePercentagePerDevice
    - uptimePercentage
    type: object
    x-model: AggregatedMyAppMetric

  AggregatedMyAppMetricResponse:
    properties:
      iteration_count:
        type: integer
      metrics:
        items:
          $ref: '#/definitions/AggregatedMyAppMetric'
        type: array
    required:
    - iteration_count
    - metrics
    type: object
    x-model: AggregatedMyAppMetricResponse

  AlertStatus:
    properties:
      AppHealth:
        description: Percentage of time where the AppHealth alerts were raised
        format: float
        maximum: 1
        minimum: 0
        type: number
      CpuUsage:
        description: Percentage of time where the CpuUsage alerts were raised
        format: float
        maximum: 1
        minimum: 0
        type: number
      DeviceReachability:
        description: Percentage of time where the DeviceReachability alerts were raised
        format: float
        maximum: 1
        minimum: 0
        type: number
      MemUsage:
        description: Percentage of time where the MemUsage alerts were raised
        format: float
        maximum: 1
        minimum: 0
        type: number
      NoAlert:
        description: Percentage of time where the no alerts were raised
        format: float
        maximum: 1
        minimum: 0
        type: number
    required:
    - NoAlert
    - AppHealth
    - DeviceReachability
    - CpuUsage
    - MemUsage
    type: object
    x-model: AlertStatus

  DeviceMinimal:
    properties:
      deviceId:
        type: string
      ipAddress:
        type: string
      port:
        type: integer
      totalCpu:
        type: integer
      totalMem:
        type: integer
    required:
    - deviceId
    - ipAddress
    - port
    - totalCpu
    - totalMem
    type: object
    x-model: DeviceMinimal

  DeviceDescription:
    allOf:
    - $ref: '#/definitions/DeviceMinimal'
    - type: object
      properties:
        cpuMetricsDistributionMean:
          type: number
          format: integer
        cpuMetricsDistributionStdDev:
          type: number
          format: integer
        memMetricsDistributionMean:
          type: number
          format: integer
        memMetricsDistributionStdDev:
          type: number
          format: integer
        chaosDieProb:
          type: number
          format: float
        chaosReviveProb:
          type: number
          format: float
      required:
      - cpuMetricsDistributionMean
      - cpuMetricsDistributionStdDev
      - memMetricsDistributionMean
      - memMetricsDistributionStdDev
      - chaosDieProb
      - chaosReviveProb

  IterationCount:
    properties:
      iteration_count:
        type: integer
    required:
    - iteration_count
    type: object
    x-model: IterationCount

  MyAppMinimal:
    properties:
      myAppId:
        type: string
      name:
        type: string
    required:
    - myAppId
    - name
    type: object
    x-model: MyAppMinimal

  SimulationStatisticResponse:
    properties:
      alerts:
        $ref: '#/definitions/AlertStatus'
      averageUptime:
        description: Average of the all myApp uptime percentage for all the iterations
        items:
          format: float
          maximum: 1
          minimum: 0
          type: number
        type: array
      maxIterationCount:
        type: integer
      minIterationCount:
        type: integer
      totalEnergyConsumption:
        items:
          format: float
          minimum: 0
          type: number
        type: array
      totalNumberOfSamplings:
        type: integer
    required:
    - totalNumberOfSamplings
    - minIterationCount
    - maxIterationCount
    - averageUptime
    - totalEnergyConsumption
    - alerts
    type: object
    x-model: SimulationStatisticResponse

info:
  title: APIs for Fog Director Simulator
  version: '0.0'

paths:
  /simulator_frontend/aggregated_device_metric/v1:
    get:
      description: Retrieve the post-aggregated metrics related to the Devices
      operationId: get_simulator_frontend_aggregated_device_metric_v1
      parameters:
      - in: query
        name: iteration_count
        required: false
        type: integer
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: device_ids
        required: false
        type: array
      responses:
        '200':
          description: HTTP/200
          schema:
            $ref: '#/definitions/AggregatedDeviceMetricResponse'
      tags:
      - simulator_frontend

  /simulator_frontend/aggregated_my_app_metric/v1:
    get:
      description: Retrieve the post-aggregated metrics related to the My Apps
      operationId: get_simulator_frontend_aggregated_my_app_metric_v1
      parameters:
      - in: query
        name: iteration_count
        required: false
        type: integer
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: my_app_ids
        required: false
        type: array
      responses:
        '200':
          description: HTTP/200
          schema:
            $ref: '#/definitions/AggregatedMyAppMetricResponse'
      tags:
      - simulator_frontend

  /simulator_frontend/iteration_count/v1:
    get:
      description: Retrieve the current iteration count of the simulation
      operationId: get_simulator_frontend_iteration_count_v1
      parameters:
      - in: query
        name: iteration_count
        required: false
        type: integer
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: device_ids
        required: false
        type: array
      responses:
        '200':
          description: HTTP/200
          schema:
            $ref: '#/definitions/IterationCount'
      tags:
      - simulator_frontend

  /simulator_frontend/simulation_statistic/v1:
    get:
      description: Retrieve historical information related to the whole simulation
      operationId: get_simulator_frontend_simulation_statistic_v1
      parameters:
      - in: query
        minimum: 0
        name: minIterationCount
        required: false
        type: integer
      - in: query
        minimum: 0
        name: maxIterationCount
        required: false
        type: integer
      - description: TODO
        in: query
        minimum: 1
        name: totalNumberOfSamplings
        required: true
        type: integer
      responses:
        '200':
          description: HTTP/200
          schema:
            $ref: '#/definitions/SimulationStatisticResponse'
      tags:
      - simulator_frontend
  /simulator_management/device/v1:
    post:
      description: Add device to the infrastructure without adding it to FogDirector instance
      operationId: post_simulator_management_device_v1
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/DeviceDescription'
      responses:
        '201':
          description: Device correctly added to the infrastructure
      tags:
      - simulator_management


produces:
- application/json

schemes:
- http
- https

swagger: '2.0'
