DEVICE_LOW_CPU = 1
DEVICE_LOW_MEM = 2
DEVICE_DOWN = 3
DEVICE_CPU_USED = 4
DEVICE_MEM_USED = 5

MYAPP_INSTALLED = 4
MYAPP_UNINSTALLED = 5
MYAPP_STATUS = 6
JOB_STARTED = 7
JOB_STOPPED = 8
JOB_STATUS = 9
APP_ON_DEVICE = 10
APP_ON_DEVICE_WITH_NO_RESOURCES_CPU = 11
APP_ON_DEVICE_WITH_NO_RESOURCES_MEM = 12

MYAPP_PROFILE_LOW = "relax"
MYAPP_PROFILE_NORMAL = "normal"
MYAPP_PROFILE_HIGH = "angry"

# Alerts Type
APP_HEALTH = 0 # App is corrupted on a the device or ***has some other issue with its health***. 